spring:
  datasource:
    url: jdbc:h2:file:./data/birthday
    driver-class-name: org.h2.Driver
    username: sa
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
