name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: adopt

      - name: Setup gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Compile
        run: ./gradlew classes

      - name: Test
        run: ./gradlew test --info --stacktrace

      - name: Build
        run: ./gradlew build -x test

      - name: Boot Jar
        run: ./gradlew clean bootJar

      - name: Upload Boot Jar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: birthday-discord-bot
          path: build/libs/birthday-discord-bot*.jar
